/* generated by dia/codegen.py */
class IA 
{
public:
	int avancer ();
	int avancer (int nbCases);
	int avancerNord ();
	int avancerNord (int nbCases);
	void tourner (int degrees);
	void tournerDroite ( );
	void tournerGauche ();
	int reculer (int nbCases);
	void agir ();
protected:
	Robot robot;
};

class IA_Simple : IA 
{
public:
	void agir ();
};

class IA_2 : IA 
{
public:
	void agir ();
};

class IA_Test : IA 
{
public:
	void agir ();
};

class Robot 
{
public:
	int avancer ();
	int avancer (int nbCases);
	int avancerNord ();
	int avancerNord (int nbCases);
	void tourner (int degrees);
	void tournerDroite ( );
	void tournerGauche ();
	int reculer (int nbCases);
	void agir ();
	CarteSimple carteScannee;
private:
	Senseur[ ] senseurs;
	Actuateur[ ] actuateurs;
};

