PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX erdf: <https://erdf.opendatasoft.com/erdf/>
PREFIX prod: <https://erdf.opendatasoft.com/typeProductionAnnee/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbpedia-owl: <http://fr.dbpedia.org/ontology/>
PREFIX dbpedia-fr: <http://fr.dbpedia.org/page/>
PREFIX dbpedia: <http://dbpedia.org/page/>
PREFIX semanco-eu: <http://semanco-tools.eu/ontology-releases/eu/semanco/ontology/SEMANCO/SEMANCO.owl#>


#Nombre d'installations, puissance générées en 2010 et 2014 par type de production

Select ?typeprod ?nbIns ?puissance ?label
Where
{
        ?x dbpedia-owl:year  ?annee;
            erdf:NbInstallation ?nbIns ;
            rdf:type ?typeprod;
            dbpedia:Megawatt ?puissance.
        ?annee rdfs:label ?label
        Filter regex (?label, "201[0,4] en France")

}

Order by ?typeprod



