export AMDAPPSDKROOT="/comptes/goualard-f/local/AMDAPPSDK-2.9-1"
export OPENCL_VENDOR_PATH="/comptes/goualard-f/local/AMDAPPSDK-2.9-1/etc/OpenCL/vendors/"
export LD_LIBRARY_PATH=":/usr/local/opt/xenomai/lib:/usr/local/opt/Client_oracle:/comptes/goualard-f/local/AMDAPPSDK-2.9-1/lib/x86_64/:/comptes/goualard-f/local/AMDAPPSDK-2.9-1/lib/x86/"
export CPLUS_INCLUDE_PATH=:/comptes/goualard-f/local/include
