# Requête sur le dataset "fa-par-region"
# Auteurs : Alexis Giraudet & Thomas Minier, M1 ALMA 2015
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbpedia: <http://fr.dbpedia.org/resource/>
PREFIX erdf: <https://erdf.opendatasoft.com/>
PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

# Requête donnant le nombre d'installations par type de production par ordre décroissant
SELECT *
WHERE {
	?uri erdf:NbInstallation ?nbInstallation .
}
ORDER BY DESC(?nbInstallation)
